name: sociodotabuleiro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: 3.4.1
  app_links_platform_interface: 1.1.0
  auto_size_text: 3.0.0
  badges: 2.0.2
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
  cloud_firestore: 4.17.3
  cloud_firestore_platform_interface: 6.2.3
  cloud_firestore_web: 3.12.3
  cloud_functions: 4.7.4
  cloud_functions_platform_interface: 5.5.26
  cloud_functions_web: 4.9.4
  collection: 1.18.0
  csv: 6.0.0
  easy_debounce: 2.0.1
  equatable: 2.0.5
  firebase_analytics: 10.10.5
  firebase_analytics_platform_interface: 3.10.6
  firebase_analytics_web: 0.5.7+5
  firebase_auth: 4.19.5
  firebase_auth_platform_interface: 7.2.6
  firebase_auth_web: 5.11.5
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_performance: 0.9.4+5
  firebase_performance_platform_interface: 0.1.4+33
  firebase_performance_web: 0.1.6+5
  firebase_storage: ^11.6.8
  flutter_animate: 4.5.0
  flutter_blurhash: 0.8.2
  flutter_cache_manager: 3.3.1
  flutter_credit_card: 4.0.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_rating_bar: 4.0.1
  flutter_secure_storage: 9.2.2
  flutter_secure_storage_linux: 1.2.1
  flutter_secure_storage_macos: 3.1.2
  flutter_secure_storage_platform_interface: 1.1.2
  flutter_secure_storage_web: 1.2.1
  flutter_secure_storage_windows: 3.1.2
  flutter_stripe: 10.1.1
  flutter_stripe_web: 5.1.0
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  geoflutterfire2: ^2.3.15
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  gotrue: 1.12.6
  hive: 2.2.3
  http: 1.2.1
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  json_path: 0.7.2
  mask_text_input_formatter: 2.9.0
  mime_type: 1.0.0
  octo_image: 2.0.0
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  postgrest: 1.5.2
  provider: 6.1.2
  realtime_client: 1.4.0
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  storage_client: 1.5.4
  stream_transform: 2.1.0
  stripe_android: 10.1.1
  stripe_ios: 10.1.0
  stripe_js: 3.4.0
  stripe_platform_interface: 10.1.1
  supabase: 1.11.11
  supabase_flutter: 1.10.24
  synchronized: 3.1.0
  timeago: 3.6.1
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  webview_flutter: 4.7.0
  webview_flutter_android: 3.15.0
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.12.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  rxdart: 0.27.7
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: CategoriasSdT
      fonts:
        - asset: assets/fonts/categorias_SdT.ttf

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

